# Generated by Django 5.2.8 on 2025-11-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
